version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
        - checkout
        - python/load-cache
        - python/install-deps
        - python/save-cache
        - run:
            command: echo "Add your damn tests"
            name: Test

  deploy:
    executor: python/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - df:34:25:83:57:0e:46:2c:39:f7:e8:ee:b1:a2:fa:37
      - run:
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -p ${LIVE_PORT} ${LIVE_IP} >> ~/.ssh/known_hosts
          name: Add server to known hosts
      - run:
          command: ssh -p "${LIVE_PORT}" "${LIVE_USER}"@"${LIVE_IP}" "cd /var/www/lol_esports_calendar_generator; git pull; cd frontend; npm run build; service gunicorn-lol restart"
          name: Deploy

workflows:
  main:
    jobs:
      - test:
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
