version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  deploy:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: echo "This works"
          name: Deploy

workflows:
  main:
    jobs:
      - deploy
